# Generated by Django 6.0.5 on 2026-05-17 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО автора')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('genre', models.CharField(choices=[('fantasy', 'Фэнтези'), ('sci-fi', 'Научная фантастика'), ('detective', 'Детектив'), ('classic', 'Классика'), ('romance', 'Романтика'), ('thriller', 'Триллер'), ('horror', 'Ужасы'), ('adventure', 'Приключения'), ('mystery', 'Мистика'), ('historical', 'Историческая литература'), ('biography', 'Биография'), ('autobiography', 'Автобиография'), ('poetry', 'Поэзия'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('satire', 'Сатира'), ('dystopia', 'Антиутопия'), ('utopia', 'Утопия'), ('young-adult', 'Подростковая литература'), ('children', 'Детская литература'), ('non-fiction', 'Нон-фикшн'), ('self-help', 'Саморазвитие'), ('psychology', 'Психология'), ('philosophy', 'Философия'), ('science', 'Наука'), ('education', 'Образование'), ('business', 'Бизнес'), ('economics', 'Экономика'), ('politics', 'Политика'), ('religion', 'Религия'), ('travel', 'Путешествия'), ('cookbook', 'Кулинария'), ('art', 'Искусство'), ('health', 'Здоровье'), ('technology', 'Технологии'), ('programming', 'Программирование')], max_length=50, verbose_name='Жанр')),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('inventory_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Инвентарный_номер')),
                ('status', models.CharField(choices=[('excellent', 'Отлично'), ('good', 'Хорошо'), ('average', 'Среднее'), ('bad', 'Плохое')], max_length=50, verbose_name='Состояние')),
                ('location', models.CharField(max_length=100, verbose_name='Место_хранения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Экземпляр',
                'verbose_name_plural': 'Экземпляры',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(verbose_name='Срок_возврата')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance', verbose_name='Экземпляр книги')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
            },
        ),
    ]
