# Generated by Django 6.0.5 on 2026-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'verbose_name': 'Экземпляр книги', 'verbose_name_plural': 'Экземпляры книг'},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('reserved', 'Забронировано'), ('on_hand', 'На руках'), ('archive', 'В архиве')], default='available', max_length=50, verbose_name='Статус экземпляра'),
        ),
    ]
